support_server: "https://discord.gg/52C8MtW54M" # Your Discord server invite link. Leave empty if you don't have one.
api_token: "http://45.90.13.151:6041/?url=${link}&apikey=${apikey}" # Your Byte API token (purchase one at https://discord.gg/PSvdeDbFYV)

command_logger:
  enabled: true # Whether or not the bot should log commands.
  webhook: "https://discord.com/api/webhooks/1256919653943607388/-eh8cxxfmmsfLA2ChmwrxRwRyTemtq8taSKGifWiFIbMY-ANAYeIF1EWYw-hL__angI8" # The webhook URL for command logs.
