support_server: "" # Your Discord server invite link. Leave empty if you don't have one.
api_token: "" # Your Byte API token (purchase one at https://discord.gg/PSvdeDbFYV)

command_logger:
  enabled: false # Whether or not the bot should log commands.
  webhook: "" # The webhook URL for command logs.
